spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  jpa:
    hibernate:
      ddl-auto: none # 프로덕션에서는 자동 생성 비활성화
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  frontend:
    baseUrl: http://amoroso.blue

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.example.amorosobackend: INFO

server:
  error:
    include-stacktrace: never # 프로덕션에서 스택트레이스 노출 방지
